version: "3.8"
services:
  web:
    container_name: content_project
    build: ./app
    image: 276629917546.dkr.ecr.us-west-1.amazonaws.com/django_project:django_project_web
    command: python manage.py runserver 0.0.0.0:8000
    #command: gunicorn content_project.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_NAME=content_project_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=contentproject.crjedstgvmjh.us-west-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      # - VIRTUAL_HOST=ec2-13-57-7-72.us-west-1.compute.amazonaws.com
      # - VIRTUAL_PORT=8000
