# Generated by Django 3.1.1 on 2022-08-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('location', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('hospitals', models.ManyToManyField(related_name='departments', to='hospitals.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_color', models.TextField(unique=True)),
                ('cc_code', models.TextField(unique=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_center', to='hospitals.department')),
            ],
        ),
    ]
