# Generated by Django 3.1.1 on 2022-08-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_center',
            name='cc_code',
            field=models.IntegerField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='cc_color',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
