# Generated by Django 3.1.1 on 2022-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20220825_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_center',
            name='cc_code',
            field=models.IntegerField(unique=True),
        ),
    ]
