# Generated by Django 3.1.1 on 2022-08-25 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostedcontent',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_contents', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='checkedcontent',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_contents', to='hospitals.hospital'),
        ),
    ]
