# Generated by Django 3.1.1 on 2022-08-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20220825_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostedcontent',
            old_name='name',
            new_name='title',
        ),
    ]
