# Generated by Django 3.1.1 on 2022-08-25 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0003_auto_20220825_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedcontent',
            name='checked_contents',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
