# Generated by Django 3.1.1 on 2022-08-26 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0005_auto_20220825_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedcontent',
            name='users',
        ),
        migrations.AddField(
            model_name='checkedcontent',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
