# Generated by Django 3.1.1 on 2022-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20220826_0404'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='hostedcontent',
        #     name='location',
        # ),
        migrations.RenameField(
            model_name='hostedcontent',
            old_name='location',
            new_name='folder_path',
        ),
        migrations.AddField(
            model_name='hostedcontent',
            name='content_format',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hostedcontent',
            name='content_subtype',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hostedcontent',
            name='content_type',
            field=models.TextField(null=True),
        ),
        # migrations.AddField(
        #     model_name='hostedcontent',
        #     name='folder_path',
        #     field=models.CharField(blank=True, max_length=300),
        # ),
        migrations.AddField(
            model_name='hostedcontent',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hostedcontent',
            name='revision',
            field=models.IntegerField(null=True),
        ),
    ]
