# Generated by Django 3.1.1 on 2022-08-27 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0007_auto_20220827_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedcontent',
            name='user',
        ),
        migrations.AddField(
            model_name='checkedcontent',
            name='users',
            field=models.ManyToManyField(related_name='checked_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostedcontent',
            name='content_type',
            field=models.CharField(choices=[['type 1', 'Reports'], ['type 2', 'Drawings'], ['type 3', 'Specs'], ['type 4', 'Other']], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hostedcontent',
            name='folder_path',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
