# Generated by Django 3.1.1 on 2022-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_auto_20220827_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedcontent',
            name='content_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostedcontent',
            name='content_subtype',
            field=models.CharField(blank=True, choices=[['Base Plan', 'Type 1'], ['As-Built', 'Type 2'], ['Occupancy Plan', 'Type 3'], ['Vacancy Plan', 'Type 4'], ['Smoke Compartment', 'Type 5'], ['Life Safety', 'Type 6'], ['Air Relationship', 'Type 7'], ['Contract and Leasing Exhibits', 'Type 8'], ['Maps and Signage', 'Type 9'], ['Other', 'Type 10']], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hostedcontent',
            name='content_type',
            field=models.CharField(choices=[['Reports', 'Reports'], ['Drawings', 'Drawings'], ['Specs', 'Specs'], ['Other', 'Other']], max_length=20, null=True),
        ),
    ]
