# Generated by Django 3.1.1 on 2022-09-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_auto_20220901_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedcontent',
            name='content_subtype',
            field=models.CharField(blank=True, choices=[['Base Plan', 'Base Plan'], ['As-Built', 'As-Built'], ['Occupancy Plan', 'Occupancy Plan'], ['Vacancy Plan', 'Vacancy Plan'], ['Smoke Compartment', 'Smoke Compartment'], ['Life Safety', 'Life Safety'], ['Air Relationship', 'Air Relationship'], ['Contract and Leasing Exhibits', 'Contract and Leasing Exhibits'], ['Maps and Signage', 'Maps and Signage'], ['Other', 'Other']], max_length=50, null=True),
        ),
    ]
